<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;
use App\Utilities\Core;
use App\Models\District;



class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districtsData = [
    ['name' => 'BANIKOARA', 'municipality_id' => 1],
    ['name' => 'FOUNOUGO', 'municipality_id' => 1],
    ['name' => 'GOMPAROU', 'municipality_id' => 1],
    ['name' => 'GOUMORI', 'municipality_id' => 1],
    ['name' => 'KOKEY', 'municipality_id' => 1],
    ['name' => 'KOKIBOROU', 'municipality_id' => 1],
    ['name' => 'OUNET', 'municipality_id' => 1],
    ['name' => 'SOMPEREKOU', 'municipality_id' => 1],
    ['name' => 'SOROKO', 'municipality_id' => 1],
    ['name' => 'TOURA', 'municipality_id' => 1],
    ['name' => 'BAGOU', 'municipality_id' => 2],
    ['name' => 'GOGOUNOU', 'municipality_id' => 2],
    ['name' => 'GOUNAROU', 'municipality_id' => 2],
    ['name' => 'SORI', 'municipality_id' => 2],
    ['name' => 'SOUGOU-KPANTROSSI', 'municipality_id' => 2],
    ['name' => 'WARA', 'municipality_id' => 2],
    ['name' => 'ANGARADEBOU', 'municipality_id' => 3],
    ['name' => 'BENSEKOU', 'municipality_id' => 3],
    ['name' => 'DONWARI', 'municipality_id' => 3],
    ['name' => 'KANDI 1', 'municipality_id' => 3],
    ['name' => 'KANDI 2', 'municipality_id' => 3],
    ['name' => 'KANDI 3', 'municipality_id' => 3],
    ['name' => 'KASSAKOU', 'municipality_id' => 3],
    ['name' => 'SAAH', 'municipality_id' => 3],
    ['name' => 'SAM', 'municipality_id' => 3],
    ['name' => 'SONSORO', 'municipality_id' => 3],
    ['name' => 'BIRNI LAFIA', 'municipality_id' => 4],
    ['name' => 'BOGO-BOGO', 'municipality_id' => 4],
    ['name' => 'KARIMAMA', 'municipality_id' => 4],
    ['name' => 'KOMPA', 'municipality_id' => 4],
    ['name' => 'MONSEY', 'municipality_id' => 4],
    ['name' => 'GAROU', 'municipality_id' => 5],
    ['name' => 'GUENE', 'municipality_id' => 5],
    ['name' => 'MADECALI', 'municipality_id' => 5],
    ['name' => 'MALANVILLE', 'municipality_id' => 5],
    ['name' => 'TOUMBOUTOU', 'municipality_id' => 5],
    ['name' => 'LIBANTE', 'municipality_id' => 6],
    ['name' => 'LIBOUSSOU', 'municipality_id' => 6],
    ['name' => 'LOUGOU', 'municipality_id' => 6],
    ['name' => 'SEGBANA', 'municipality_id' => 6],
    ['name' => 'SOKOTINDJI', 'municipality_id' => 6],
    ['name' => 'BOUKOMBE', 'municipality_id' => 7],
    ['name' => 'DIPOLI', 'municipality_id' => 7],
    ['name' => 'KORONTIERE', 'municipality_id' => 7],
    ['name' => 'KOUSSOUCOINGOU', 'municipality_id' => 7],
    ['name' => 'MANTA', 'municipality_id' => 7],
    ['name' => 'NATTA', 'municipality_id' => 7],
    ['name' => 'TABOTA', 'municipality_id' => 7],
    ['name' => 'COBLY', 'municipality_id' => 8],
    ['name' => 'DATORI', 'municipality_id' => 8],
    ['name' => 'KOUNTORI', 'municipality_id' => 8],
    ['name' => 'TAPOGA', 'municipality_id' => 8],
    ['name' => 'BRIGNAMARO', 'municipality_id' => 9],
    ['name' => 'FIROU', 'municipality_id' => 9],
    ['name' => 'KAOBAGOU', 'municipality_id' => 9],
    ['name' => 'KEROU', 'municipality_id' => 9],
    ['name' => 'BIRNI', 'municipality_id' => 10],
    ['name' => 'CHABI-COUMA', 'municipality_id' => 10],
    ['name' => 'FOO-TANCE', 'municipality_id' => 10],
    ['name' => 'GUILMARO', 'municipality_id' => 10],
    ['name' => 'KOUANDE', 'municipality_id' => 10],
    ['name' => 'OROUKAYO', 'municipality_id' => 10],
    ['name' => 'DASSARI', 'municipality_id' => 11],
    ['name' => 'GOUANDE', 'municipality_id' => 11],
    ['name' => 'MATERI', 'municipality_id' => 11],
    ['name' => 'NODI', 'municipality_id' => 11],
    ['name' => 'TANTEGA', 'municipality_id' => 11],
    ['name' => 'TCHANHOUNCOSSI', 'municipality_id' => 11],
    ['name' => 'KOTOPOUNGA', 'municipality_id' => 12],
    ['name' => 'KOUABA', 'municipality_id' => 12],
    ['name' => 'KOUANDATA', 'municipality_id' => 12],
    ['name' => 'NATITINGOU 1', 'municipality_id' => 12],
    ['name' => 'NATITINGOU 2', 'municipality_id' => 12],
    ['name' => 'NATITINGOU 3', 'municipality_id' => 12],
    ['name' => 'PEPORIYAKOU', 'municipality_id' => 12],
    ['name' => 'PERMA', 'municipality_id' => 12],
    ['name' => 'TCHOUMI-TCHOUMI', 'municipality_id' => 12],
    ['name' => 'GNEMASSON', 'municipality_id' => 13],
    ['name' => 'PEHUNCO', 'municipality_id' => 13],
    ['name' => 'TOBRE', 'municipality_id' => 13],
    ['name' => 'COTIAKOU', 'municipality_id' => 14],
    ['name' => 'N’DAHONTA', 'municipality_id' => 14],
    ['name' => 'TAIACOU', 'municipality_id' => 14],
    ['name' => 'TANGUIETA', 'municipality_id' => 14],
    ['name' => 'TANONGOU', 'municipality_id' => 14],
    ['name' => 'KOUARFA', 'municipality_id' => 15],
    ['name' => 'TAMPEGRE', 'municipality_id' => 15],
    ['name' => 'TOUKOUNTOUNA', 'municipality_id' => 15],
    ['name' => 'ABOMEY-CALAVI', 'municipality_id' => 16],
    ['name' => 'AKASSATO', 'municipality_id' => 16],
    ['name' => 'GODOMEY', 'municipality_id' => 16],
    ['name' => 'GOLO-DJIGBE', 'municipality_id' => 16],
    ['name' => 'HEVIE', 'municipality_id' => 16],
    ['name' => 'KPANROUN', 'municipality_id' => 16],
    ['name' => 'OUEDO', 'municipality_id' => 16],
    ['name' => 'TOGBA', 'municipality_id' => 16],
    ['name' => 'ZINVIE', 'municipality_id' => 16],
    ['name' => 'AGBANOU', 'municipality_id' => 17],
    ['name' => 'AHOUANNONZOUN', 'municipality_id' => 17],
    ['name' => 'ALLADA CENTRE', 'municipality_id' => 17],
    ['name' => 'ATTOGON', 'municipality_id' => 17],
    ['name' => 'AVAKPA', 'municipality_id' => 17],
    ['name' => 'AYOU', 'municipality_id' => 17],
    ['name' => 'HINVI', 'municipality_id' => 17],
    ['name' => 'LISSEGAZOUN', 'municipality_id' => 17],
    ['name' => 'LON-AGONMEY', 'municipality_id' => 17],
    ['name' => 'SEKOU', 'municipality_id' => 17],
    ['name' => 'TOGOUDO', 'municipality_id' => 17],
    ['name' => 'TOKPA', 'municipality_id' => 17],
    ['name' => 'AGANMALOME', 'municipality_id' => 18],
    ['name' => 'AGBANTO', 'municipality_id' => 18],
    ['name' => 'AGONKANME', 'municipality_id' => 18],
    ['name' => 'DEDOME', 'municipality_id' => 18],
    ['name' => 'DEKANME', 'municipality_id' => 18],
    ['name' => 'KPOMASSE CENTRE', 'municipality_id' => 18],
    ['name' => 'SEGBEYA', 'municipality_id' => 18],
    ['name' => 'SEGBOHOUE', 'municipality_id' => 18],
    ['name' => 'TOKPA-DOME', 'municipality_id' => 18],
    ['name' => 'AVLEKETE', 'municipality_id' => 19],
    ['name' => 'DJEGBADJI', 'municipality_id' => 19],
    ['name' => 'GAKPE', 'municipality_id' => 19],
    ['name' => 'HOUAKPE-DAHO', 'municipality_id' => 19],
    ['name' => 'OUIDAH 1', 'municipality_id' => 19],
    ['name' => 'OUIDAH 2', 'municipality_id' => 19],
    ['name' => 'OUIDAH 3', 'municipality_id' => 19],
    ['name' => 'OUIDAH 4', 'municipality_id' => 19],
    ['name' => 'PAHOU', 'municipality_id' => 19],
    ['name' => 'SAVI', 'municipality_id' => 19],
    ['name' => 'AHOMEY-LOKPO', 'municipality_id' => 20],
    ['name' => 'DEKANMEY', 'municipality_id' => 20],
    ['name' => 'GANVIE 1', 'municipality_id' => 20],
    ['name' => 'GANVIE 2', 'municipality_id' => 20],
    ['name' => 'HOUEDO-AGUEKON', 'municipality_id' => 20],
    ['name' => 'SO-AVA', 'municipality_id' => 20],
    ['name' => 'VEKKY', 'municipality_id' => 20],
    ['name' => 'AGUE', 'municipality_id' => 21],
    ['name' => 'COLLI', 'municipality_id' => 21],
    ['name' => 'COUSSI', 'municipality_id' => 21],
    ['name' => 'DAME', 'municipality_id' => 21],
    ['name' => 'DJANGLANME', 'municipality_id' => 21],
    ['name' => 'HOUEGBO', 'municipality_id' => 21],
    ['name' => 'KPOME', 'municipality_id' => 21],
    ['name' => 'SEHOUE', 'municipality_id' => 21],
    ['name' => 'SEY', 'municipality_id' => 21],
    ['name' => 'TOFFO', 'municipality_id' => 21],
    ['name' => 'AVAME', 'municipality_id' => 22],
    ['name' => 'AZOHOUE-ALIHO', 'municipality_id' => 22],
    ['name' => 'AZOHOUE-CADA', 'municipality_id' => 22],
    ['name' => 'TORI-BOSSITO', 'municipality_id' => 22],
    ['name' => 'TORI-CADA', 'municipality_id' => 22],
    ['name' => 'TORI-GARE', 'municipality_id' => 22],
    ['name' => 'ADJAN', 'municipality_id' => 23],
    ['name' => 'DAWE', 'municipality_id' => 23],
    ['name' => 'DJIGBE', 'municipality_id' => 23],
    ['name' => 'DODJI-BATA', 'municipality_id' => 23],
    ['name' => 'HEKANME', 'municipality_id' => 23],
    ['name' => 'KOUNDOKPOE', 'municipality_id' => 23],
    ['name' => 'SEDJE-DENOU', 'municipality_id' => 23],
    ['name' => 'SEDJE-HOUEGOUDO', 'municipality_id' => 23],
    ['name' => 'TANGBO', 'municipality_id' => 23],
    ['name' => 'YOKPO', 'municipality_id' => 23],
    ['name' => 'ZE', 'municipality_id' => 23],
    ['name' => 'BEMBEREKE', 'municipality_id' => 24],
    ['name' => 'BEROUBOUAY', 'municipality_id' => 24],
    ['name' => 'BOUANRI', 'municipality_id' => 24],
    ['name' => 'GAMIA', 'municipality_id' => 24],
    ['name' => 'INA', 'municipality_id' => 24],
    ['name' => 'BASSO', 'municipality_id' => 25],
    ['name' => 'BOUCA', 'municipality_id' => 25],
    ['name' => 'DERASSI', 'municipality_id' => 25],
    ['name' => 'DUNKASSA', 'municipality_id' => 25],
    ['name' => 'KALALE', 'municipality_id' => 25],
    ['name' => 'PEONGA', 'municipality_id' => 25],
    ['name' => 'BORI', 'municipality_id' => 26],
    ['name' => 'GBEGOUROU', 'municipality_id' => 26],
    ['name' => 'N’DALI', 'municipality_id' => 26],
    ['name' => 'OUENOU', 'municipality_id' => 26],
    ['name' => 'SIRAROU', 'municipality_id' => 26],
    ['name' => 'BIRO', 'municipality_id' => 27],
    ['name' => 'GNONKOURAKALI', 'municipality_id' => 27],
    ['name' => 'NIKKI', 'municipality_id' => 27],
    ['name' => 'OUENOU', 'municipality_id' => 27],
    ['name' => 'SEREKALE', 'municipality_id' => 27],
    ['name' => 'SUYA', 'municipality_id' => 27],
    ['name' => 'TASSO', 'municipality_id' => 27],
    ['name' => '1ER ARRONDISSEMENT', 'municipality_id' => 28],
    ['name' => '2EME ARRONDISSEMENT', 'municipality_id' => 28],
    ['name' => '3EME ARRONDISSEMENT', 'municipality_id' => 28],
    ['name' => 'GNINSY', 'municipality_id' => 29],
    ['name' => 'GUINAGOUROU', 'municipality_id' => 29],
    ['name' => 'KPANE', 'municipality_id' => 29],
    ['name' => 'KPEBIE', 'municipality_id' => 29],
    ['name' => 'PERERE', 'municipality_id' => 29],
    ['name' => 'SONTOU', 'municipality_id' => 29],
    ['name' => 'FO-BOURE', 'municipality_id' => 30],
    ['name' => 'SEKERE', 'municipality_id' => 30],
    ['name' => 'SIKKI', 'municipality_id' => 30],
    ['name' => 'SINENDE', 'municipality_id' => 30],
    ['name' => 'ALAFIAROU', 'municipality_id' => 31],
    ['name' => 'BETEROU', 'municipality_id' => 31],
    ['name' => 'GORO', 'municipality_id' => 31],
    ['name' => 'KIKA', 'municipality_id' => 31],
    ['name' => 'SANSON', 'municipality_id' => 31],
    ['name' => 'TCHAOUROU', 'municipality_id' => 31],
    ['name' => 'TCHATCHOU', 'municipality_id' => 31],
    ['name' => 'AGOUA', 'municipality_id' => 32],
    ['name' => 'AKPASSI', 'municipality_id' => 32],
    ['name' => 'ATOKOLIBE', 'municipality_id' => 32],
    ['name' => 'BANTE', 'municipality_id' => 32],
    ['name' => 'BOBE', 'municipality_id' => 32],
    ['name' => 'GOUKA', 'municipality_id' => 32],
    ['name' => 'KOKO', 'municipality_id' => 32],
    ['name' => 'LOUGBA', 'municipality_id' => 32],
    ['name' => 'PIRA', 'municipality_id' => 32],
    ['name' => 'AKOFFODJOULE', 'municipality_id' => 33],
    ['name' => 'DASSA 1', 'municipality_id' => 33],
    ['name' => 'DASSA 2', 'municipality_id' => 33],
    ['name' => 'GBAFO', 'municipality_id' => 33],
    ['name' => 'KERE', 'municipality_id' => 33],
    ['name' => 'KPINGNI', 'municipality_id' => 33],
    ['name' => 'LEMA', 'municipality_id' => 33],
    ['name' => 'PAOUINGNAN', 'municipality_id' => 33],
    ['name' => 'SOCLOGBO', 'municipality_id' => 33],
    ['name' => 'TRE', 'municipality_id' => 33],
    ['name' => 'AKLAMPA', 'municipality_id' => 34],
    ['name' => 'ASSANTE', 'municipality_id' => 34],
    ['name' => 'GLAZOUE', 'municipality_id' => 34],
    ['name' => 'GOME', 'municipality_id' => 34],
    ['name' => 'KPAKPAZA', 'municipality_id' => 34],
    ['name' => 'MAGOUMI', 'municipality_id' => 34],
    ['name' => 'OUEDEME', 'municipality_id' => 34],
    ['name' => 'SOKPONTA', 'municipality_id' => 34],
    ['name' => 'THIO', 'municipality_id' => 34],
    ['name' => 'ZAFFE', 'municipality_id' => 34],
    ['name' => 'CHALLA-OGOI', 'municipality_id' => 35],
    ['name' => 'DJEGBE', 'municipality_id' => 35],
    ['name' => 'GBANLIN', 'municipality_id' => 35],
    ['name' => 'IKEMON', 'municipality_id' => 35],
    ['name' => 'KILIBO', 'municipality_id' => 35],
    ['name' => 'LAMINOU', 'municipality_id' => 35],
    ['name' => 'ODOUGBA', 'municipality_id' => 35],
    ['name' => 'OUESSE', 'municipality_id' => 35],
    ['name' => 'TOUI', 'municipality_id' => 35],
    ['name' => 'DJALLOUKOU', 'municipality_id' => 36],
    ['name' => 'DOUME', 'municipality_id' => 36],
    ['name' => 'GOBADA', 'municipality_id' => 36],
    ['name' => 'KPATABA', 'municipality_id' => 36],
    ['name' => 'LAHOTAN', 'municipality_id' => 36],
    ['name' => 'LEMA', 'municipality_id' => 36],
    ['name' => 'LOGOZOHE', 'municipality_id' => 36],
    ['name' => 'MONKPA', 'municipality_id' => 36],
    ['name' => 'OTTOLA', 'municipality_id' => 36],
    ['name' => 'OUESSE', 'municipality_id' => 36],
    ['name' => 'SAVALOU-AGA', 'municipality_id' => 36],
    ['name' => 'SAVALOU-AGBADO', 'municipality_id' => 36],
    ['name' => 'SAVALOU-ATTAKE', 'municipality_id' => 36],
    ['name' => 'TCHETTI', 'municipality_id' => 36],
    ['name' => 'ADIDO', 'municipality_id' => 37],
    ['name' => 'BESSE', 'municipality_id' => 37],
    ['name' => 'BONI', 'municipality_id' => 37],
    ['name' => 'KABOUA', 'municipality_id' => 37],
    ['name' => 'OFFE', 'municipality_id' => 37],
    ['name' => 'OKPARA', 'municipality_id' => 37],
    ['name' => 'PLATEAU', 'municipality_id' => 37],
    ['name' => 'SAKIN', 'municipality_id' => 37],
    ['name' => 'APLAHOUE', 'municipality_id' => 38],
    ['name' => 'ATOMEY', 'municipality_id' => 38],
    ['name' => 'AZOVE', 'municipality_id' => 38],
    ['name' => 'DEKPO-CENTRE', 'municipality_id' => 38],
    ['name' => 'GODOHOU', 'municipality_id' => 38],
    ['name' => 'KISSAMEY', 'municipality_id' => 38],
    ['name' => 'LONKLY', 'municipality_id' => 38],
    ['name' => 'ADJINTIMEY', 'municipality_id' => 39],
    ['name' => 'BETOUMEY', 'municipality_id' => 39],
    ['name' => 'DJAKOTOMEY 1', 'municipality_id' => 39],
    ['name' => 'DJAKOTOMEY 2', 'municipality_id' => 39],
    ['name' => 'GOHOMEY', 'municipality_id' => 39],
    ['name' => 'HOUEGAMEY', 'municipality_id' => 39],
    ['name' => 'KINKINHOUE', 'municipality_id' => 39],
    ['name' => 'KOKOHOUE', 'municipality_id' => 39],
    ['name' => 'KPOBA', 'municipality_id' => 39],
    ['name' => 'SOKOUHOUE', 'municipality_id' => 39],
    ['name' => 'AYOMI', 'municipality_id' => 40],
    ['name' => 'DEVE', 'municipality_id' => 40],
    ['name' => 'HONTON', 'municipality_id' => 40],
    ['name' => 'LOKOGOHOUE', 'municipality_id' => 40],
    ['name' => 'MADJRE', 'municipality_id' => 40],
    ['name' => 'TOTA', 'municipality_id' => 40],
    ['name' => 'TOTCHANGNI CENTRE', 'municipality_id' => 40],
    ['name' => 'ADJAHONME', 'municipality_id' => 41],
    ['name' => 'AHOGBEYA', 'municipality_id' => 41],
    ['name' => 'AYAHOHOUE', 'municipality_id' => 41],
    ['name' => 'DJOTTO', 'municipality_id' => 41],
    ['name' => 'HONDJIN', 'municipality_id' => 41],
    ['name' => 'KLOUEKANMEY', 'municipality_id' => 41],
    ['name' => 'LANTA', 'municipality_id' => 41],
    ['name' => 'TCHIKPE', 'municipality_id' => 41],
    ['name' => 'ADOUKANDJI', 'municipality_id' => 42],
    ['name' => 'AHODJINNAKO', 'municipality_id' => 42],
    ['name' => 'AHOMADEGBE', 'municipality_id' => 42],
    ['name' => 'BANIGBE', 'municipality_id' => 42],
    ['name' => 'GNIZOUNME', 'municipality_id' => 42],
    ['name' => 'HLASSAME', 'municipality_id' => 42],
    ['name' => 'LALO', 'municipality_id' => 42],
    ['name' => 'LOKOGBA', 'municipality_id' => 42],
    ['name' => 'TCHITO', 'municipality_id' => 42],
    ['name' => 'TOHOU', 'municipality_id' => 42],
    ['name' => 'ZALLI', 'municipality_id' => 42],
    ['name' => 'ADJIDO', 'municipality_id' => 43],
    ['name' => 'AVEDJIN', 'municipality_id' => 43],
    ['name' => 'DOKO', 'municipality_id' => 43],
    ['name' => 'HOUEDOGLI', 'municipality_id' => 43],
    ['name' => 'MISSINKO', 'municipality_id' => 43],
    ['name' => 'TANNOU-GOLA', 'municipality_id' => 43],
    ['name' => 'TOVIKLIN', 'municipality_id' => 43],
    ['name' => 'ALEDJO', 'municipality_id' => 44],
    ['name' => 'BASSILA', 'municipality_id' => 44],
    ['name' => 'MANIGRI', 'municipality_id' => 44],
    ['name' => 'PENESSOULOU', 'municipality_id' => 44],
    ['name' => 'ANANDANA', 'municipality_id' => 45],
    ['name' => 'COPARGO', 'municipality_id' => 45],
    ['name' => 'PABEGOU', 'municipality_id' => 45],
    ['name' => 'SINGRE', 'municipality_id' => 45],
    ['name' => 'BAREI', 'municipality_id' => 46],
    ['name' => 'BARIENOU', 'municipality_id' => 46],
    ['name' => 'BELLEFOUNGOU', 'municipality_id' => 46],
    ['name' => 'BOUGOU', 'municipality_id' => 46],
    ['name' => 'DJOUGOU 1', 'municipality_id' => 46],
    ['name' => 'DJOUGOU 2', 'municipality_id' => 46],
    ['name' => 'DJOUGOU 3', 'municipality_id' => 46],
    ['name' => 'KOLOCONDE', 'municipality_id' => 46],
    ['name' => 'ONKLOU', 'municipality_id' => 46],
    ['name' => 'PARTAGO', 'municipality_id' => 46],
    ['name' => 'PELEBINA', 'municipality_id' => 46],
    ['name' => 'SERO', 'municipality_id' => 46],
    ['name' => 'BADJOUDE', 'municipality_id' => 47],
    ['name' => 'KOMDE', 'municipality_id' => 47],
    ['name' => 'OUAKE', 'municipality_id' => 47],
    ['name' => 'SEMERE 1', 'municipality_id' => 47],
    ['name' => 'SEMERE 2', 'municipality_id' => 47],
    ['name' => 'TCHALINGA', 'municipality_id' => 47],
    ['name' => '10EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '11EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '12EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '13EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '1ER ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '2EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '3EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '4EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '5EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '6EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '7EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '8EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => '9EME ARRONDISSEMENT', 'municipality_id' => 48],
    ['name' => 'ADOHOUN', 'municipality_id' => 49],
    ['name' => 'ATCHANNOU', 'municipality_id' => 49],
    ['name' => 'ATHIEME', 'municipality_id' => 49],
    ['name' => 'DEDEKPOE', 'municipality_id' => 49],
    ['name' => 'KPINNOU', 'municipality_id' => 49],
    ['name' => 'AGBODJI', 'municipality_id' => 50],
    ['name' => 'BADAZOUIN', 'municipality_id' => 50],
    ['name' => 'BOPA', 'municipality_id' => 50],
    ['name' => 'GBAKPODJI', 'municipality_id' => 50],
    ['name' => 'LOBOGO', 'municipality_id' => 50],
    ['name' => 'POSSOTOME', 'municipality_id' => 50],
    ['name' => 'YEGODOE', 'municipality_id' => 50],
    ['name' => 'AGATOGBO', 'municipality_id' => 51],
    ['name' => 'AKODEHA', 'municipality_id' => 51],
    ['name' => 'COME', 'municipality_id' => 51],
    ['name' => 'OUEDEME-PEDAH', 'municipality_id' => 51],
    ['name' => 'OUMAKO', 'municipality_id' => 51],
    ['name' => 'ADJAHA', 'municipality_id' => 52],
    ['name' => 'AGOUE', 'municipality_id' => 52],
    ['name' => 'AVLO', 'municipality_id' => 52],
    ['name' => 'DJANGLANMEY', 'municipality_id' => 52],
    ['name' => 'GBEHOUE', 'municipality_id' => 52],
    ['name' => 'GRAND-POPO', 'municipality_id' => 52],
    ['name' => 'SAZUE', 'municipality_id' => 52],
    ['name' => 'DAHE', 'municipality_id' => 53],
    ['name' => 'DOUTOU', 'municipality_id' => 53],
    ['name' => 'HONHOUE', 'municipality_id' => 53],
    ['name' => 'HOUEYOGBE', 'municipality_id' => 53],
    ['name' => 'SE', 'municipality_id' => 53],
    ['name' => 'ZOUNGBONOU', 'municipality_id' => 53],
    ['name' => 'AGAME', 'municipality_id' => 54],
    ['name' => 'HOUIN', 'municipality_id' => 54],
    ['name' => 'KOUDO', 'municipality_id' => 54],
    ['name' => 'LOKOSSA', 'municipality_id' => 54],
    ['name' => 'OUEDEME-ADJA', 'municipality_id' => 54],
    ['name' => 'ADJARRA 1', 'municipality_id' => 55],
    ['name' => 'ADJARRA 2', 'municipality_id' => 55],
    ['name' => 'AGLOGBE', 'municipality_id' => 55],
    ['name' => 'HONVIE', 'municipality_id' => 55],
    ['name' => 'MALANHOUI', 'municipality_id' => 55],
    ['name' => 'MEDEDJONOU', 'municipality_id' => 55],
    ['name' => 'ADJOHOUN', 'municipality_id' => 56],
    ['name' => 'AKPADANOU', 'municipality_id' => 56],
    ['name' => 'AWONOU', 'municipality_id' => 56],
    ['name' => 'AZOWLISSE', 'municipality_id' => 56],
    ['name' => 'DEME', 'municipality_id' => 56],
    ['name' => 'GANGBAN', 'municipality_id' => 56],
    ['name' => 'KODE', 'municipality_id' => 56],
    ['name' => 'TOGBOTA', 'municipality_id' => 56],
    ['name' => 'AVAGBODJI', 'municipality_id' => 57],
    ['name' => 'HOUEDOME', 'municipality_id' => 57],
    ['name' => 'ZOUNGAME', 'municipality_id' => 57],
    ['name' => 'AKPRO-MISSERETE', 'municipality_id' => 58],
    ['name' => 'GOME-SOTA', 'municipality_id' => 58],
    ['name' => 'KATAGON', 'municipality_id' => 58],
    ['name' => 'VAKON', 'municipality_id' => 58],
    ['name' => 'ZOUNGBOME', 'municipality_id' => 58],
    ['name' => 'ATCHOUKPA', 'municipality_id' => 59],
    ['name' => 'AVRANKOU', 'municipality_id' => 59],
    ['name' => 'DJOMON', 'municipality_id' => 59],
    ['name' => 'GBOZOUNME', 'municipality_id' => 59],
    ['name' => 'KOUTI', 'municipality_id' => 59],
    ['name' => 'OUANHO', 'municipality_id' => 59],
    ['name' => 'SADO', 'municipality_id' => 59],
    ['name' => 'AFFAME', 'municipality_id' => 60],
    ['name' => 'ATCHONSA', 'municipality_id' => 60],
    ['name' => 'BONOU', 'municipality_id' => 60],
    ['name' => 'DAME-WOGON', 'municipality_id' => 60],
    ['name' => 'HOUNVIGUE', 'municipality_id' => 60],
    ['name' => 'DANGBO', 'municipality_id' => 61],
    ['name' => 'DEKIN', 'municipality_id' => 61],
    ['name' => 'GBEKO', 'municipality_id' => 61],
    ['name' => 'HOUEDOMEY', 'municipality_id' => 61],
    ['name' => 'HOZIN', 'municipality_id' => 61],
    ['name' => 'KESSOUNOU', 'municipality_id' => 61],
    ['name' => 'ZOUNGUE', 'municipality_id' => 61],
    ['name' => '1ER ARRONDISSEMENT', 'municipality_id' => 62],
    ['name' => '2EME ARRONDISSEMENT', 'municipality_id' => 62],
    ['name' => '3EME ARRONDISSEMENT', 'municipality_id' => 62],
    ['name' => '4EME ARRONDISSEMENT', 'municipality_id' => 62],
    ['name' => '5EME ARRONDISSEMENT', 'municipality_id' => 62],
    ['name' => 'AGBLANGANDAN', 'municipality_id' => 63],
    ['name' => 'AHOLOUYEME', 'municipality_id' => 63],
    ['name' => 'DJEREGBE', 'municipality_id' => 63],
    ['name' => 'EKPE', 'municipality_id' => 63],
    ['name' => 'SEME-PODJI', 'municipality_id' => 63],
    ['name' => 'TOHOUE', 'municipality_id' => 63],
    ['name' => 'ADJA-OUERE', 'municipality_id' => 64],
    ['name' => 'IKPINLE', 'municipality_id' => 64],
    ['name' => 'KPOULOU', 'municipality_id' => 64],
    ['name' => 'MASSE', 'municipality_id' => 64],
    ['name' => 'OKO-AKARE', 'municipality_id' => 64],
    ['name' => 'TATONNONKON', 'municipality_id' => 64],
    ['name' => 'BANIGBE', 'municipality_id' => 65],
    ['name' => 'DAAGBE', 'municipality_id' => 65],
    ['name' => 'IFANGNI', 'municipality_id' => 65],
    ['name' => 'KO-KOUMOLOU', 'municipality_id' => 65],
    ['name' => 'LAGBE', 'municipality_id' => 65],
    ['name' => 'TCHAADA', 'municipality_id' => 65],
    ['name' => 'ADAKPLAME', 'municipality_id' => 66],
    ['name' => 'IDIGNY', 'municipality_id' => 66],
    ['name' => 'KETOU', 'municipality_id' => 66],
    ['name' => 'KPANKOU', 'municipality_id' => 66],
    ['name' => 'ODOMETA', 'municipality_id' => 66],
    ['name' => 'OKPOMETA', 'municipality_id' => 66],
    ['name' => 'AHOYEYE', 'municipality_id' => 67],
    ['name' => 'IGANA', 'municipality_id' => 67],
    ['name' => 'ISSABA', 'municipality_id' => 67],
    ['name' => 'POBE', 'municipality_id' => 67],
    ['name' => 'TOWE', 'municipality_id' => 67],
    ['name' => 'AGUIDI', 'municipality_id' => 68],
    ['name' => 'ITA-DJEBOU', 'municipality_id' => 68],
    ['name' => 'SAKETE 1', 'municipality_id' => 68],
    ['name' => 'SAKETE 2', 'municipality_id' => 68],
    ['name' => 'TAKON', 'municipality_id' => 68],
    ['name' => 'YOKO', 'municipality_id' => 68],
    ['name' => 'AGBOKPA', 'municipality_id' => 69],
    ['name' => 'DETOHOU', 'municipality_id' => 69],
    ['name' => 'DJEGBE', 'municipality_id' => 69],
    ['name' => 'HOUNLI', 'municipality_id' => 69],
    ['name' => 'SEHOUN', 'municipality_id' => 69],
    ['name' => 'VIDOLE', 'municipality_id' => 69],
    ['name' => 'ZOUNZONME', 'municipality_id' => 69],
    ['name' => 'ADANHONDJIGO', 'municipality_id' => 70],
    ['name' => 'ADINGNIGON', 'municipality_id' => 70],
    ['name' => 'AGBANGNIZOUN', 'municipality_id' => 70],
    ['name' => 'KINTA', 'municipality_id' => 70],
    ['name' => 'KPOTA', 'municipality_id' => 70],
    ['name' => 'LISSAZOUNME', 'municipality_id' => 70],
    ['name' => 'SAHE', 'municipality_id' => 70],
    ['name' => 'SINWE', 'municipality_id' => 70],
    ['name' => 'TANVE', 'municipality_id' => 70],
    ['name' => 'ZOUNGOUNDO', 'municipality_id' => 70],
    ['name' => 'AGONGOINTO', 'municipality_id' => 71],
    ['name' => 'AVOGBANNA', 'municipality_id' => 71],
    ['name' => 'BOHICON 1', 'municipality_id' => 71],
    ['name' => 'BOHICON 2', 'municipality_id' => 71],
    ['name' => 'GNIDJAZOUN', 'municipality_id' => 71],
    ['name' => 'LISSEZOUN', 'municipality_id' => 71],
    ['name' => 'OUASSAHO', 'municipality_id' => 71],
    ['name' => 'PASSAGON', 'municipality_id' => 71],
    ['name' => 'SACLO', 'municipality_id' => 71],
    ['name' => 'SODOHOME', 'municipality_id' => 71],
    ['name' => 'ADOGBE', 'municipality_id' => 72],
    ['name' => 'GOUNLI', 'municipality_id' => 72],
    ['name' => 'HOUEKO', 'municipality_id' => 72],
    ['name' => 'HOUEKO', 'municipality_id' => 72], // Duplicata possible dans les données source, vérifiez si c'est intentionnel
    ['name' => 'HOUEIN-HOUNSO', 'municipality_id' => 72], // Correction d'une faute de frappe probable: HOUEIN-HOUNSO au lieu de HOUEKO
    ['name' => 'LAINTA-COGBE', 'municipality_id' => 72],
    ['name' => 'NAOGON', 'municipality_id' => 72],
    ['name' => 'SOLI', 'municipality_id' => 72],
    ['name' => 'ZOGBA', 'municipality_id' => 72],
    ['name' => 'AGONDJI', 'municipality_id' => 73],
    ['name' => 'AGOUNA', 'municipality_id' => 73],
    ['name' => 'DAN', 'municipality_id' => 73],
    ['name' => 'DJIDJA-CENTRE', 'municipality_id' => 73],
    ['name' => 'DOHOUIME', 'municipality_id' => 73],
    ['name' => 'GOBAIX', 'municipality_id' => 73],
    ['name' => 'HOUTO', 'municipality_id' => 73],
    ['name' => 'MONSOUROU', 'municipality_id' => 73],
    ['name' => 'MOUGNON', 'municipality_id' => 73],
    ['name' => 'OUMBEGAME', 'municipality_id' => 73],
    ['name' => 'SETTO', 'municipality_id' => 73],
    ['name' => 'ZOUNKON', 'municipality_id' => 73],
    ['name' => 'DASSO', 'municipality_id' => 74],
    ['name' => 'OUINHI-CENTRE', 'municipality_id' => 74],
    ['name' => 'SAGON', 'municipality_id' => 74],
    ['name' => 'TOHOUES', 'municipality_id' => 74],
    ['name' => 'AGONLIN-HOUEGBO', 'municipality_id' => 75],
    ['name' => 'BANAME', 'municipality_id' => 75],
    ['name' => 'DON-TAN', 'municipality_id' => 75],
    ['name' => 'DOVI', 'municipality_id' => 75],
    ['name' => 'KPEDEKPO', 'municipality_id' => 75],
    ['name' => 'ZAGNANADO-CENTRE', 'municipality_id' => 75],
    ['name' => 'ALLAHE', 'municipality_id' => 76],
    ['name' => 'ASSANLIN', 'municipality_id' => 76],
    ['name' => 'HOUNGOME', 'municipality_id' => 76],
    ['name' => 'KPAKPAME', 'municipality_id' => 76],
    ['name' => 'KPOZOUN', 'municipality_id' => 76],
    ['name' => 'ZA-KPOTA', 'municipality_id' => 76],
    ['name' => 'ZA-TANTA', 'municipality_id' => 76],
    ['name' => 'ZEKO', 'municipality_id' => 76],
    ['name' => 'AKIZA', 'municipality_id' => 77],
    ['name' => 'AVLAME', 'municipality_id' => 77],
    ['name' => 'CANA 1', 'municipality_id' => 77],
    ['name' => 'CANA 2', 'municipality_id' => 77],
    ['name' => 'DOME', 'municipality_id' => 77],
    ['name' => 'KOUSSOUKPA', 'municipality_id' => 77],
    ['name' => 'KPOKISSA', 'municipality_id' => 77],
    ['name' => 'MASSI', 'municipality_id' => 77],
    ['name' => 'TANWE-HESSOU', 'municipality_id' => 77],
    ['name' => 'ZOGBODOMEY-CENTRE', 'municipality_id' => 77],
    ['name' => 'ZOUKOU', 'municipality_id' => 77],
];

foreach ($districtsData as $index => $data) {

            District::create([
                'name' => $data['name'],
                'municipality_id' => $data['municipality_id'],
            ]);
        }

    }
}
